-- PUBLIC."TRANSACTION" definition

-- Drop table

-- DROP TABLE PUBLIC."TRANSACTION";

CREATE TABLE PUBLIC."TRANSACTION" (
                                      ID INTEGER DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C228BB07_D73F_4A8D_A97A_CD449EDDD4FC") NOT NULL AUTO_INCREMENT,
                                      ID_COMPANY VARCHAR(14) NOT NULL,
                                      "TYPE" VARCHAR(1) NOT NULL,
                                      AMOUNT DECIMAL(10,2) NOT NULL,
                                      ACC_ORIGIN VARCHAR(100) NOT NULL,
                                      ACC_DESTINATION VARCHAR(100) NOT NULL,
                                      CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC."TRANSACTION" (ID);



INSERT INTO PUBLIC."TRANSACTION" (ID_COMPANY,"TYPE",AMOUNT,ACC_ORIGIN,ACC_DESTINATION) VALUES
('19000400000100','C',1235.45,'0123456','987654'),
('19000400000100','D',845.15,'0123456','951753');
