-- PUBLIC.COMPANY definition

-- Drop table

-- DROP TABLE PUBLIC.COMPANY;

CREATE TABLE PUBLIC.COMPANY (
    ID INTEGER DEFAULT  NOT NULL AUTO_INCREMENT,
    COMPANY_NAME VARCHAR(100) NOT NULL,
    COMPANY_ID VARCHAR(100) NOT NULL,
    CONSTRAINT CONSTRAINT_6 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_6 ON PUBLIC.COMPANY (ID);


-- PUBLIC."TRANSACTION" definition

-- Drop table

-- DROP TABLE PUBLIC."TRANSACTION";

CREATE TABLE PUBLIC."TRANSACTION" (
    ID INTEGER DEFAULT  NOT NULL AUTO_INCREMENT,
    "TYPE" VARCHAR(1) NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    ACC_ORIGIN VARCHAR(100) NOT NULL,
    ACC_DESTINATION VARCHAR(100) NOT NULL,
    ID_COMPANY INTEGER,
    CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_5A ON PUBLIC."TRANSACTION" (ID);
CREATE INDEX TRANSACTION_FK_INDEX_F ON PUBLIC."TRANSACTION" (ID_COMPANY);





